### ISSUE TITLE
Tangut Yinchuan glyphs are not fully rendered

### ISSUE THREAD

**Issue by dscorbett** [simoncozens/crowbar#10]
With [Tangut Yinchuan 13.001](https://www.babelstone.co.uk/Fonts/Yinchuan.html#Download), the SVGs of the glyphs of many characters, e.g. ⟨𘟷⟩, are mangled.
![𘟷](https://user-images.githubusercontent.com/1124347/85557953-486e6c80-b5f6-11ea-8c15-3fbe207496ba.png)

**Comment by simoncozens** [comment]
That's a harfbuzzjs bug, but I'll fix it.

**Comment by simoncozens** [comment]
Should be fixed.
