### ISSUE TITLE
Activating/deactivating a feature does not immediately affect the rendered output

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/crowbar#11]
The (textual) buffer contents change, but the rendered output does not change until I move the cursor to a different line and back.

**Comment by simoncozens** [comment]
Yes, the partial shaping stuff keeps state in a very dirty way to try to get the right glyphstring to the SVG renderer. I need to make sure the output component gets re-rendered when things change *and* when the user hovers over a table row.

**Comment by simoncozens** [comment]
I've fixed the state-change issue (not deployed yet), but there's another problem: Harfbuzz.js is *sometimes* ignoring my feature string!
