### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/crowbar#16]
These are some options that woukd be handy for debugging:
- direction (can’t be always guessed correctly)
- script (ditto, nothing fancy an input field should do)
- language
- preserve default ignorables
- features (also nothing fancy, an input field should do; it is important for me to be able to apply features to parts of the text)
- face index (for font collections, low priority)

**Comment by khaledhosny** [comment]
I see feature are there, but they apply to the whole string, but I want to, say, enable `salt` for the 3rd character only.

**Comment by simoncozens** [comment]
I've added direction, script and language so far. Will work on the others.

**Comment by khaledhosny** [comment]
Thanks!

**Comment by n8willis** [comment]
I *think* this would fall under the same general-options category, but I'll open a separate issue if not: it would be nice to be able to choose the specific OTL script tag, so that a user can debug Indic1-era behavior or compare it to Indic2 by selecting (e.g.) `deva` or `dev2`.

**Comment by simoncozens** [comment]
I'm not entirely sure you can do that with Harfbuzz. It's not just a matter of choosing script type, but of choosing shaper behaviour. I did a quick experiment: when I set `hb-shape --script=deva`, I got dev2 script behaviour, and when I chose `hb-shape --script=dev2`, I didn't get any Indic shaping because dev2 is not a recognised ISO-15924 tag so it went for the default shaper instead.

@khaledhosny, do you know any way to manually choose between dev, dev2 (and even USE-flavoured dev3) with HB?

**Comment by khaledhosny** [comment]
AFAIK, the selection is automatic `dev3` → `dev2` → `deva` based on what the font supports. But you might be able to influence this with HarfBuzz [private sub-tags](https://github.com/harfbuzz/harfbuzz/issues/2680), e.g. `deva-hbscdev2`, but you can’t use this to select a different shaper.

**Comment by khaledhosny** [comment]
> but you can’t use this to select a different shaper.

So you need to correctly set the script first to select the Devanagari shaper, then set the language with the private script sub-tag to select `dev2` vs `deva`, but you can’t use it to select USE shaper AFAIK.

**Comment by simoncozens** [comment]
OK, I've done your feature string thing, but there is a weird problem in harfbuzzjs I can't track down. When you shape the same text multiple times but change the feature string, sometimes the feature string change gets ignored... presumably something being cached somewhere?

**Comment by khaledhosny** [comment]
I don’t know, but I doubt HarfBuzz has such caching issue or it would have been discovered by now (it caches shape plans, but the cache key takes user features into account).

**Comment by simoncozens** [comment]
I've added the ability to type arbitrary language strings in the dropdown, which will allow you to use private language subtags.

**Comment by simoncozens** [comment]
And now I've added support for buffer flags and TrueType collections.

**Comment by khaledhosny** [comment]
Looks great, thanks! (I’m seeing `undefined :` under lookup names, no idea what this is).

**Comment by simoncozens** [comment]
Oops. That's when it's trying to read the fontTools `Debg` stuff.

**Comment by simoncozens** [comment]
Fixed now

**Comment by khaledhosny** [comment]
Looks good, thanks again!
