### ISSUE TITLE
Unparse lookups to AFDKO .fea

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/crowbar#4]

**Comment by Richard57** [comment]
As a likely user, I suspect that sometimes my lookups may not decompile to AFDKO.  I use a lot of (chained) context substitutions, and the input and output sequences may have different lengths.  Additionally, I have also used 'degenerate' ligature and multiple substitutions that include substitution of a single glyph for a single glyph.  I would appreciate graceful handling of any consequent decompilation failures, e.g. decompiling to 'UNDECOMPILABLE!'.

**Comment by simoncozens** [comment]
I've just managed to decompile your dalekh_si to AFDKO, so you should be fine. :-) However, I *probably* won't do this part in Crowbar anyway, but in another OpenType debugger I'm currently working on. (Doing it in Crowbar would involve porting a *lot* of Python to JavaScript, and the new debugger is already in Python, so can immediately make use of the decompiler.)

**Comment by Richard57** [comment]
That's good news about the successful decompilation, but are you sure you decompiled context substitution lookup 94 ("shift_mai_sam") correctly?  For 3 to 5 input glyphs, it merges the first two and splits the last.  Its purpose is to move the glyph uni1A7B to the end of a sequence of marks above. To compile the lookup properly, there has to be awareness that the first lookup changes two glyphs to one.

**Comment by Richard57** [comment]
Actually, that lookup 94 might not be a problem, as the start position for subordinate lookup is less than the number of input glyphs.  Lookup 84 (mai_kam_shift) would be the challenge as its third context has 2 glyphs but a start position of 2.  That will be gone from Version 0.012 as iOS (on iPhone7 at least) doesn't support it.
