### ISSUE TITLE
How harfbuzz.wasm is built

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/crowbar#51]
I’m trying to expose the version of HarfBuzz used, but the symbol I want is not seem to be exposed in harfbuzz.wasm, and there is not documentation how it was built and from what sources.

**Comment by simoncozens** [comment]
Yeah, and that's bad. It should be scripted or in GHA. The short answer is that it's an embarrassing mess.

The version currently in use is harfbuzzjs@f2959be with HB 2.7.2 with [this patch](https://github.com/harfbuzz/harfbuzz/issues/2468#issuecomment-643488169) applied.

**Comment by khaledhosny** [comment]
That is what I feared. I’m working on updating harfbuzzjs version of HarfBuzz, and will then see if I can build the patched version and update crowbar’s HarfBuzz.

**Comment by khaledhosny** [comment]
Thanks!
