### ISSUE TITLE
Glyphs are always shown as coe points

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/crowbar#57]
Everything seems to be reported as code points now:
<img width="1077" alt="Screenshot 2023-05-11 at 7 27 23 PM" src="https://github.com/simoncozens/crowbar/assets/93914/f7723d84-7ea7-438f-ab5d-60e22b2b29a8">

**Comment by simoncozens** [comment]
I can't reproduce this, what script were you using here?

**Comment by khaledhosny** [comment]
It works now, may be it was a cache issue.
