### ISSUE TITLE
Question: What does "recursing to lookup" mean

### ISSUE THREAD

**Issue by waruyama** [simoncozens/crowbar#60]
I cannot find anything about this this in the [OpenType specification](https://learn.microsoft.com/en-us/typography/opentype/spec/). Searching for "recursing" or "recursive" does not yield any results. I always assumed that features are processed sequencially, but this sounds as if one feature is called from another. Can you provide a link where this is explained?

![image](https://github.com/simoncozens/crowbar/assets/43434568/eac27650-906b-4fd3-b370-b7196d2bb77b)

**Comment by waruyama** [comment]
As so often writing down the question makes it much easier to find the solution. "Resursion" is most probably what the OpenType spec calls ["nested" lookup tables](https://learn.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-5-contextual-substitution-subtable) for GPOS lookup type 7 and type 8, as well as GSUB lookup type 5, type 6.

If I am right, please feel free to simply close the issue.

**Comment by waruyama** [comment]
Hm, I found another example that is a bit more complex. This recurses from "calt" to "fina", so it cannot be a "nested" lookup. 

My next guess would be that an entry in the FeatureVariation table is what causes the recursion.

![image](https://github.com/simoncozens/crowbar/assets/43434568/3dbaebfd-2497-4a4a-8755-c4fd1fa4d95f)

**Comment by simoncozens** [comment]
> "Resursion" is most probably what the OpenType spec calls ["nested" lookup tables](https://learn.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-5-contextual-substitution-subtable) for GPOS lookup type 7 and type 8, as well as GSUB lookup type 5, type 6.

Exactly that! In contextual lookups, one lookup calls another.

> This recurses from "calt" to "fina", so it cannot be a "nested" lookup.

It is. The part of Crowbar which tries to work out which feature a lookup belongs to is approximate. What you probably have in this font is something like:

```
# This is fairly typical for Latin handwriting/connected fonts, but it's wrong, for
# reasons not relevant to this issue.
feature fina {
    sub i by i.fina;
    # more rules here
} fina;

feature calt {
    sub f f i' by i.fina;
} calt;
```

Since the rule recursed to in the `calt` feature is exactly the same as the one in the `fina` feature, when this is compiled into the binary, the lookups will be laid out more like this:

```
lookup doFinas {
    sub i by i.fina;
} doFinas;

feature fina {
     lookup doFinas;
} fina;

feature calt {
    sub f f i' lookup doFinas;
} calt;
```

Crowbar (correctly) associates `doFinas` with the `fina` feature, but it is now shared between two features. Arguably we should probably not guess the feature of a lookup that is called through recursion.

**Comment by waruyama** [comment]
I see. You are approaching the layout process more from a font designer's point of view, while I am using Crowbar to compare the steps in HarfBuzz with my own layout engine, so I do not care if the font is implemented correctly as long as the processing steps and the output for the layout are the same. I am fine knowing that I can simply ignore those feature names in the recursion for my use case. Thanks so much for taking your time.

**Comment by simoncozens** [comment]
Yes, this is a debugging tool for font designers!
